#:schema https://mise.en.dev/schema/mise-task.json
[tasks.copy_savegame]
description = "copy the savegame"
run = "cp ~/.local/share/Replicube/progress.dat ./test/large_progress.dat"

[tasks.dump]
depends = [ ":copy_savegame" ]
description = "Uses golang to dump the contents of my savegame"
run = "mise //replicube_lua_exporter_golang:dump_mysavegame"

[hooks]
# Automatically install/update hooks when tools are installed
postinstall = "hk install --mise"
