#:schema https://mise.en.dev/schema/mise-task.json

[env]
_.path = [ "./target/debug" ]

[tasks.build]
description = "Build the rust CLI"
run = "cargo build"

[tasks.test]
description = "Test the rust CLI"
depends = [ ":build", ":clean_tests_rust" ]
run = "replicube_lua_exporter_rust -f ../test/large_progress.dat -o ../test/solutions_rust"

[tasks.clean_tests_rust]
description = "Clean rust test dir"
run = "rm -rf ./test/solutions_rust"
